[package]
name = "phire"
version = "0.4.0"
edition = "2021"
license = "GPL-3.0-only"

[lib]

[features]
default = ["log", "play", "video"]
closed = []
log = ["dep:tracing-subscriber", "dep:colored"]
play = []
video = ["dep:prpr-avc"]

[dependencies]
chinese-number = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
cfg-if = { workspace = true }
chardetng = { workspace = true }
concat-string = { workspace = true }
csv = { workspace = true }
fastblur = { workspace = true }
fluent = { workspace = true }
fluent-syntax = { workspace = true }
glyph_brush = { workspace = true }
image = { workspace = true }
intl-memoizer = { workspace = true }
lru = { workspace = true }
lyon = { workspace = true }
macroquad = { workspace = true }
nalgebra = { workspace = true }
once_cell = { workspace = true }
ordered-float = { workspace = true }
phf = { workspace = true }
rand = { workspace = true }
rand_pcg = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
symphonia = { workspace = true }
sys-locale = { workspace = true }
tempfile = { workspace = true }
tracing = { workspace = true }
unic-langid = { workspace = true }
zip = { workspace = true }

byteorder = { workspace = true }
chrono = { workspace = true }
hex = { workspace = true }
hmac = { workspace = true }
miniz_oxide = { workspace = true }
obfstr = { workspace = true }
sha2 = { workspace = true }
subtle = { workspace = true }
libc = { workspace = true }
bitflags = { workspace = true }
color-thief = { workspace = true }

tracing-subscriber = { workspace = true, optional = true }
colored = { workspace = true, optional = true }

prpr-avc = { path = "../prpr-avc", optional = true }
lazy_static = { workspace = true }
rustc-hash = { workspace = true }

[target.'cfg(not(any(target_os = "android", target_os = "ios", target_env = "ohos")))'.dependencies]
rfd = { workspace = true }
open = { workspace = true }

[target.'cfg(target_os = "ios")'.dependencies]
objc = { workspace = true }
objc-foundation = { workspace = true }
objc_id = { workspace = true }
block = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
ndk-context = { workspace = true }
sasa = { workspace = true, default-features = false, features = ["oboe"] }

[target.'cfg(not(any(target_os = "android", target_env = "ohos")))'.dependencies]
sasa = { workspace = true, default-features = false, features = ["cpal"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "fs"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { workspace = true }
web-sys = { workspace = true }
js-sys = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }

[build-dependencies]
walkdir = { workspace = true }
